# Day 10: NumPy
 

In [1]:
import numpy as np

***
<br>
<b><b>1.	Create a one-dimensional all zero ndarray object with a length of 10, and then make the fifth element equal to 1.</b> </b><br>
<br>

In [23]:
ten_zeros = np.zeros(10, dtype='int32')
print("One-dimensional all zero with a length of 10:\n", ten_zeros)
ten_zeros[4] = 1
print("The fifth element is 1: \n", ten_zeros)

One-dimensional all zero with a length of 10:
 [0 0 0 0 0 0 0 0 0 0]
The fifth element is 1: 
 [0 0 0 0 1 0 0 0 0 0]


***
<br>
<b>2.Create a ndarray object with elements from 10 to 49. </b><br>
<br>

In [3]:
element1049 = np.arange(10,50, dtype='int32')
print(element1049)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


***
<br>
<b>3.Use np.random.random to create a 10 * 10 ndarray object and print out the maximum and minimum elements.</b> <br>
<br>

In [4]:
ten_ten = 10*np.random.random(10*10).reshape(10,10)
print("The minimum is ", ten_ten.min())
print("The maximum is ", ten_ten.max())
ten_ten

The minimum is  0.00588903040782407
The maximum is  9.951476674928374


array([[7.99687253e+00, 2.62104201e-01, 4.23675539e+00, 3.38353350e+00,
        4.87033657e+00, 5.22327335e+00, 2.87430812e+00, 5.12160844e+00,
        3.55849709e+00, 8.76388595e+00],
       [1.16236711e-01, 3.21018682e+00, 6.98432666e+00, 8.68144358e+00,
        4.29021891e-02, 7.73156279e+00, 9.57803290e+00, 6.67560027e+00,
        8.20905254e-01, 9.95147667e+00],
       [5.15509924e+00, 2.90820943e+00, 1.99373847e+00, 4.65735002e+00,
        5.36329649e+00, 6.62159906e+00, 8.88768188e+00, 2.98527374e+00,
        7.45306743e-01, 1.56044672e+00],
       [9.34197239e+00, 9.66124896e+00, 3.32563057e+00, 8.21323848e-01,
        3.24340402e+00, 5.52705009e+00, 2.34393161e+00, 3.02096136e+00,
        4.88853984e+00, 2.42101880e+00],
       [2.18764952e+00, 3.43102688e-01, 9.52921521e+00, 1.67858917e+00,
        5.65952294e+00, 4.49160241e+00, 6.75849437e+00, 8.25014204e+00,
        6.04978396e+00, 6.37643063e+00],
       [1.32984739e+00, 3.48328513e+00, 8.73342723e+00, 9.54174606e+00,
   

In [5]:
ten = ten_ten[np.newaxis, :]

In [6]:
ten.shape

(1, 10, 10)

In [7]:
ten

array([[[7.99687253e+00, 2.62104201e-01, 4.23675539e+00, 3.38353350e+00,
         4.87033657e+00, 5.22327335e+00, 2.87430812e+00, 5.12160844e+00,
         3.55849709e+00, 8.76388595e+00],
        [1.16236711e-01, 3.21018682e+00, 6.98432666e+00, 8.68144358e+00,
         4.29021891e-02, 7.73156279e+00, 9.57803290e+00, 6.67560027e+00,
         8.20905254e-01, 9.95147667e+00],
        [5.15509924e+00, 2.90820943e+00, 1.99373847e+00, 4.65735002e+00,
         5.36329649e+00, 6.62159906e+00, 8.88768188e+00, 2.98527374e+00,
         7.45306743e-01, 1.56044672e+00],
        [9.34197239e+00, 9.66124896e+00, 3.32563057e+00, 8.21323848e-01,
         3.24340402e+00, 5.52705009e+00, 2.34393161e+00, 3.02096136e+00,
         4.88853984e+00, 2.42101880e+00],
        [2.18764952e+00, 3.43102688e-01, 9.52921521e+00, 1.67858917e+00,
         5.65952294e+00, 4.49160241e+00, 6.75849437e+00, 8.25014204e+00,
         6.04978396e+00, 6.37643063e+00],
        [1.32984739e+00, 3.48328513e+00, 8.73342723e+00, 9.5

***
<br>
<b> 4. Create a 10 * 10 ndarray object. Set the boundary of the matrix to all 1, and the inside to all 0. </b><br>
<br> 

In [8]:
import numpy as np
matrixOnes = np.ones((10,10))
matrixZero = np.zeros((8,8))
matrixOnes[1:9, 1:9] = matrixZero
print(matrixOnes.astype('int32'))

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


***
<br>
<b>5. Create a random 5 * 5 matrix and sort the matrix according to the third column.  </b><br>
<br> 

In [9]:
five_matrix = np.random.randint(10, size=(5,5))
print("Orginal Matrix:\n", five_matrix)
five_matrix[:, 2].sort()
print("Sort the matrix according to the 3rd column:\n", five_matrix)

Orginal Matrix:
 [[6 3 3 4 6]
 [3 6 1 7 0]
 [0 8 0 5 2]
 [2 9 8 8 7]
 [0 5 5 6 1]]
Sort the matrix according to the 3rd column:
 [[6 3 0 4 6]
 [3 6 1 7 0]
 [0 8 3 5 2]
 [2 9 5 8 7]
 [0 5 8 6 1]]


***
<br>
<b>6. Create a two-dimensional matrix and exchange the elements of two rows.</b><br>
<br> 

In [10]:
two_dimensional = np.array([[1,2,3], [4,5,6]])

In [11]:
print(f"Original two dimentional:\n {two_dimensional}")
print("The shape of the matrix is", two_dimensional.shape)
print("The no. of dimension of the matrix is", two_dimensional.ndim)
print("The total of elements of the matrix is", two_dimensional.size)

Original two dimentional:
 [[1 2 3]
 [4 5 6]]
The shape of the matrix is (2, 3)
The no. of dimension of the matrix is 2
The total of elements of the matrix is 6


In [12]:
temp = two_dimensional[0].copy()
two_dimensional[0] = two_dimensional[1]
two_dimensional[1] = temp

In [13]:
print(f"After exchanging elements in two dimentional:\n {two_dimensional}")

After exchanging elements in two dimentional:
 [[4 5 6]
 [1 2 3]]


***
<br>
<b>7. Transform a one-dimensional array into a binary representation matrix. For example:

[1,2,3] 

Converts to 

[[0,0,1], 

[0,1,0], 

[0,1,1]]<br>
<br> 

In [15]:
val = np.array([1,2,3])
print(val)

value = []
for i in range(len(val)):
    value.append(np.binary_repr(val[i], width=3)) 

val1 = []    
for i in range(len(value)):
    val1.append(value[i])
    
valfirst = [int(i) for i in str(val1[0])]
valsecond = [int(i) for i in str(val1[1])]
valthird = [int(i) for i in str(val1[2])]

binary_matrix = np.array([valfirst, valsecond, valthird])
binary_matrix

[1 2 3]


array([[0, 0, 1],
       [0, 1, 0],
       [0, 1, 1]])

***
<br>
<b>8.Create a 5 * 5 matrix and subtract the average value of each row from the elements in the matrix. </b><br>
<br> 

In [16]:
five_matrix = np.random.randint(10, size=(5,5))

In [17]:
print(five_matrix)

[[4 0 9 3 1]
 [0 7 8 8 5]
 [7 3 9 5 2]
 [1 4 9 8 0]
 [4 1 6 9 3]]


In [18]:
for i in range(5):
    avg = five_matrix[i, :].mean()
    print("average for row ", i+1, " is ", avg)
    five_matrix[i, :] = np.subtract(five_matrix[i, :], avg)

average for row  1  is  3.4
average for row  2  is  5.6
average for row  3  is  5.2
average for row  4  is  4.4
average for row  5  is  4.6


In [19]:
print("5*5 matrix is subtracted by its average value of the elements in each row\n", five_matrix)

5*5 matrix is subtracted by its average value of the elements in each row
 [[ 0 -3  5  0 -2]
 [-5  1  2  2  0]
 [ 1 -2  3  0 -3]
 [-3  0  4  3 -4]
 [ 0 -3  1  4 -1]]


***

<br>
<b>9. Given a one-dimensional array, negate all elements between 3 and 8. </b><br>
<br> 

In [20]:
one_dimension = np.arange(10)

negate = (one_dimension >=3) & (one_dimension <=8)
one_dimension[negate] *= -1

print("Negation of all elements between 3 and 8:\n", one_dimension)

Negation of all elements between 3 and 8:
 [ 0  1  2 -3 -4 -5 -6 -7 -8  9]


***
<br>
<b>10.	Use five different methods to extract the integer part of a random array. </b><br>
<br> 

In [21]:
import numpy as np
from numpy.random import default_rng

#Using Generator, which provides a wide array of functions and used to replace with RandomState. 
#It maanges state and generates random bits.
#default_rng is the recommended constructor for the random number class Generator
rng = np.random.default_rng()

#method 1
method1 = np.round(10*np.random.random(9)).reshape(3,3)
print("Method 1 using np.random.random, rounding off floats using np.round(10*random) :\n", method1.astype('int32'))
print("It returns random integers between 1-9 and reshapes it to 3*3. Round off to int32 and change floats astype('int')")

#method 2
method2 = np.round(10*np.random.rand(10))
print("\nMethod 2 using np.random.rand: \n", method2.astype('int32'))
print("It returns random integers between 1-9 in one dimensional array. Round off to int32 and change floats astype('int')")

#method 3
method3 = np.random.randint(10, size=(5,5))
print("\nMethod 3 using np.random.randint: \n", method3)
print("It returns random integers between 0-9 and reshapes it to 5*5 matrix.")

#method 4
method4 = rng.choice(10,3, replace=False)
print("\nMethod 4 using np.random.default_rng().choice:\n", method4)
print("It returns a list of 3 elements of random integers between 1-9.")

#method 5
method4 = rng.integers(5, size=(5,5), dtype='int32')
print("\nMethod 5 using np.random.default_rng().integers: \n", method4)
print("It returns random integers between 0-5 and reshapes it to 5*5 matrix.")

Method 1 using np.random.random, rounding off floats using np.round(10*random) :
 [[6 7 1]
 [7 4 4]
 [4 1 8]]
It returns random integers between 1-9 and reshapes it to 3*3. Round off to int32 and change floats astype('int')

Method 2 using np.random.rand: 
 [2 4 3 7 2 1 1 6 6 1]
It returns random integers between 1-9 in one dimensional array. Round off to int32 and change floats astype('int')

Method 3 using np.random.randint: 
 [[1 3 0 2 6]
 [9 5 6 7 3]
 [9 0 8 7 3]
 [6 3 8 8 5]
 [2 5 8 7 5]]
It returns random integers between 0-9 and reshapes it to 5*5 matrix.

Method 4 using np.random.default_rng().choice:
 [7 1 8]
It returns a list of 3 elements of random integers between 1-9.

Method 5 using np.random.default_rng().integers: 
 [[3 2 4 2 1]
 [1 0 3 0 0]
 [4 4 3 3 1]
 [2 3 4 1 3]
 [4 0 4 2 1]]
It returns random integers between 0-5 and reshapes it to 5*5 matrix.


***
<br>
<b>11.	For a random vector whose coordinate shape is (100,2), find the distance between the 2 points.</b><br>
<br> 

In [22]:
import numpy as np
from numpy.random import default_rng
from timeit import default_timer as timer

rng = np.random.default_rng()

randomVector = rng.integers(100, size=(100,2))

#to retain original values
firstVector = randomVector.copy()
print("----------Original randomVector----------\n", firstVector)
      
#transpose so that it can calculate the distance between 2 points
transpose = randomVector.T

#use meshgrid to create coordinates of an array of the values of first dimension array and second dimension array
t1, t2 = np.meshgrid(transpose[0], transpose[1])
print("\n----------Coordinate matrices from coordinate vectors----------\n", transpose)

#using euclidean distance function
#distanceBetweenTwoPoints = np.linalg.norm(transpose[0] - transpose[1])

#calculate the euclidean distance matrix
distanceBetweenTwoPoints = np.abs(t1 - t2)

print("\n----------Distance between two points----------\n", distanceBetweenTwoPoints)

----------Original randomVector----------
 [[18 53]
 [35 89]
 [11 72]
 [48  9]
 [78 86]
 [76 93]
 [64 22]
 [29 25]
 [85 42]
 [44 15]
 [91 10]
 [45 64]
 [80 12]
 [17 74]
 [89 14]
 [71 55]
 [49 53]
 [61 64]
 [30  1]
 [82  6]
 [91 24]
 [20 44]
 [19 17]
 [46 35]
 [54 29]
 [49 90]
 [34 51]
 [47  0]
 [32 70]
 [46 70]
 [14 15]
 [ 5 17]
 [29  7]
 [72 26]
 [32 14]
 [49 86]
 [27 23]
 [56 51]
 [44  2]
 [42 35]
 [25 26]
 [62 45]
 [72 42]
 [39 52]
 [41 54]
 [58 70]
 [13 73]
 [42 69]
 [35  0]
 [83 84]
 [82 33]
 [13 63]
 [47 42]
 [11 56]
 [84 25]
 [53 94]
 [ 4 95]
 [36 89]
 [96  9]
 [23 31]
 [71 72]
 [50  4]
 [82 52]
 [23 26]
 [82 96]
 [93 78]
 [77 22]
 [85 63]
 [68 64]
 [51  3]
 [98 60]
 [40 46]
 [53 32]
 [76 83]
 [83  6]
 [85 91]
 [34 71]
 [73 79]
 [84 80]
 [59 70]
 [75 87]
 [89 47]
 [46 59]
 [29 32]
 [17 83]
 [59 98]
 [55 61]
 [63 50]
 [62  8]
 [67 12]
 [48 93]
 [35 41]
 [54 76]
 [95 27]
 [44 39]
 [51 15]
 [84 35]
 [65 97]
 [80 40]
 [61 14]]

----------Coordinate matrices from coordinate vectors--